version: "3"
services:
  cozy-crashes:
    image: ghcr.io/gabe-real/cozy-crashes:latest
    platform: linux/arm64
    container_name: cozy-crashes
    restart: always
    volumes:
      - "cozy-crashes-data:/data"

    environment:
      - "DB_URL=${DB_URL}"
      - "ENVIRONMENT=${ENVIRONMENT:-prod}"
      - "TOKEN=${TOKEN}"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=cozy-crashes"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --rolling-restart --scope cozy-crashes --label-enable
    restart: always
    environment:
      - WATCHTOWER_POLL_INTERVAL=60

volumes:
  rtuuy-discord-data:
