version: "3"
services:
  cozy-discord:
    image: ghcr.io/quiltmc/cozy-discord:latest
    container_name: cozy-discord

    restart: always
    volumes:
      - "cozy-discord-data:/data"

    environment:
      - "DB_URL=${DB_URL}"
      - "ENVIRONMENT=${ENVIRONMENT:-prod}"
      - "TOKEN=${TOKEN}"

volumes:
  cozy-discord-data:
