version: "3"
services:
  kordex-modules:
    image: ghcr.io/gabe-real/kordex-modules:latest
    platform: linux/arm64
    container_name: kordex-modules
    restart: always
    volumes:
      - "kordex-modules-data:/data"
    networks:
      - dokploy-network
    environment:
      - "DB_URL=${DB_URL}"
      - "ENVIRONMENT=${ENVIRONMENT:-prod}"
      - "TOKEN=${TOKEN}"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=kordex-modules"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --rolling-restart --scope kordex-modules --label-enable
    restart: always
    environment:
      - WATCHTOWER_POLL_INTERVAL=60

volumes:
  kordex-modules-data:

networks:
  dokploy-network:
    external: true