version: "3"
services:
  rtuuy-discord:
    image: ghcr.io/gabe-real/rtuuy-discord:latest
    container_name: crtuuy-discord
    restart: always
    volumes:
      - "rtuuy-discord-data:/data"

    environment:
      - "DB_URL=${DB_URL}"
      - "ENVIRONMENT=${ENVIRONMENT:-prod}"
      - "TOKEN=${TOKEN}"

volumes:
  rtuuy-discord-data:
